### ISSUE TITLE
About etcd

### ISSUE THREAD

**Issue by nsteinmetz** [runseb/k8s4pi#2]
You may know it but it may be easier to use [andrewpsuedonym/etcd](https://hub.docker.com/r/andrewpsuedonym/etcd/) than to build your own etc container. It may avoid a long build phase ;-)

**Comment by sebgoa** [comment]
Ah did not even realize he had built etcd as well, even though I do use the kubelet from him. thanks for the tip. It's good exercise to  build etcd on arm anyway !
